name: rtkita
version: 1.0.0+4
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluentui_system_icons: 1.1.186
  get_storage: 2.0.3
  flutter_svg: 1.1.6
  intl: 0.17.0
  url_launcher: 6.1.7
  image_picker: 0.8.6
  google_maps_flutter: 2.2.1
  # firebase: 9.0.3
  # firebase_messaging: ^14.1.2
  assets_audio_player: ^3.0.6
  cached_network_image: ^3.0.0-nullsafety
  syncfusion_flutter_charts: 20.3.61
  timeago: ^3.3.0
  qr_flutter: 4.0.0
  flutter:
    sdk: flutter
  # firebase_core: ^2.20.0
  dotted_border: ^2.1.0
  flutter_local_notifications: ^16.2.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  dcdg: 4.1.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path: assets/icon_rtpintar.png
  ios: true
  min_sdk_android: 21

flutter:
  assets:
    - assets/image/
    - assets/
  uses-material-design: true
